# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: withmakers <br> 비트코인 & 부동산 데이터분석 # ex. I m Chuan
name: DB손해보험 DS랩 # ex. DONGChuan
email: jacobgreen4477@gmail.com
company: DB손해보험
company_url: https://www.idbins.com/Index.jsp
github_url: https://github.com/withmakers # ex. https://github.com/DONGChuan
github_username: withmakers # ex. DONGChuan
favicon: favicon.ico # Image must be in assets/images
repository: withmakers/withmakers.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
# url: 

# encoding type
encoding: UTF-8

# Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# plugins
plugins:
  - jekyll-menus

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
# disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 3
paginate_path: 'page:num'

# collections
collections:
- newsletters

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /mlrealestate
    label: 부동산

  -
    href: /mlbitcoin
    label: 비트코인

#  -
#    label: Schedule
#    submenu2:
#      - href: /request/request
#        label: Data Science Lab Schedule
#      - href: /request/request2
#        label: Digital Science Lab Schedule

#  -
#    href: /todolist
#    label: To-Do-List

#  -
#    href: /about
#    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 7 # Number of repos to show

# comment by disqus-shortname
disqus-shortname: jacobgreen4477



theme: jekyll-theme-modernist